### ISSUE TITLE
Having odd trouble with this for some reason

### ISSUE THREAD

**Issue by Cassumbra** [oilboi/crafter_client#1]
Not sure what I did wrong but I can't get this to work for some reason, maybe I'm using the wrong version of minetest? (5.2.0)
![image](https://user-images.githubusercontent.com/22924188/82139768-de40fb80-97ef-11ea-8032-02978b521593.png)

**Comment by oilboi** [comment]
Oh yes, this is designed for 5.3.0-DEV, I'll add this to the info in the Readme.MD
